```{r}
library(InformationValue)
library(earth)
library(tidyverse)
library(ggplot2)
library(corrplot)


total_for_models <- read.csv("Data_files/total_for_models.csv", row.names = 1)
```

```{r}
total_for_models$churn <- ifelse(total_for_models$si2014 == 0, 1, 0)
total_for_models$si2014 <- NULL
total_for_models$data_nascita <- NULL


total_for_models$riduzione <- as.character(total_for_models$riduzione)

total_for_models$riduzione <- ifelse(total_for_models$riduzione == "OFFERTA CONVENZIONE 28\x80", "OFFERTA CONVENZIONE 28€", total_for_models$riduzione)
total_for_models$riduzione <- ifelse(total_for_models$riduzione == "OFFERTA CONVENZIONE 33\x80", "OFFERTA CONVENZIONE 33€", total_for_models$riduzione)
total_for_models$riduzione <- ifelse(total_for_models$riduzione == "OFFERTA SU QUANTITATIVO 30\x80", "OFFERTA SU QUANTITATIVO 30€", total_for_models$riduzione)
total_for_models$riduzione <- ifelse(total_for_models$riduzione == "OFFERTA SU QUANTITATIVO 44\x80", "OFFERTA SU QUANTITATIVO 44€", total_for_models$riduzione)
total_for_models$riduzione <- ifelse(total_for_models$riduzione == "PASS 60 e VOUCHER OFFERTA 30 \x80 ", "PASS 60 e VOUCHER OFFERTA 30€", total_for_models$riduzione)

total_for_models$riduzione <- as.factor(total_for_models$riduzione)
```

# Correlation Matrix

```{r}
numeric.var <- sapply(total_for_models, is.numeric)
M = cor(total_for_models[,numeric.var])
corrplot(M, method='square', type = 'lower', number.cex = 0.9, tl.cex = 0.7, tl.col = 'black')
```

# Significant Variables

```{r}
total_for_models$cap <- as.factor(total_for_models$cap)
total_for_models$sconto <- as.factor(total_for_models$sconto)
total_for_models$riduzione <- as.factor(total_for_models$riduzione)
total_for_models$tipo_pag <- as.factor(total_for_models$tipo_pag)
total_for_models$agenzia <- as.factor(total_for_models$agenzia)
total_for_models$agenzia_tipo <- as.factor(total_for_models$agenzia_tipo)
total_for_models$sesso <- as.factor(total_for_models$sesso)
total_for_models$comune <- as.factor(total_for_models$comune)
total_for_models$churn <- as.factor(total_for_models$churn)
total_for_models$cambiocap0512 <- as.factor(total_for_models$cambiocap0512)
total_for_models$nuovo_abb <- as.factor(total_for_models$nuovo_abb)
```

```{r}
sig_var <- total_for_models[ , ! names(total_for_models) %in% c("tipo_pag", "agenzia", "comune", "nmus13", "nmusei0512", "sconto")]
```

# MARS

```{r}
marsModel <- earth(churn ~ ., data=sig_var) # build model
ev <- evimp (marsModel) # estimate variable importance
```

```{r}
plot(ev)
```

# BORUTA

```{r}
library(Boruta)
# Decide if a variable is important or not using Boruta
boruta_output <- Boruta(churn ~ ., data=sig_var, doTrace=0)

boruta_signif <- names(boruta_output$finalDecision[boruta_output$finalDecision %in% c("Confirmed", "Tentative")])

print(boruta_signif)

plot(boruta_output, cex.axis=.7, las=2, xlab="", main="Variable Importance")  # plot variable importance
```

# Information value and Weight of evidence

```{r}
factor_vars <- c ("riduzione", "agenzia_tipo", "sesso", "nuovo_abb", "cambiocap0512", "cap")  # get all categorical variables
all_iv <- data.frame(VARS=factor_vars, IV=numeric(length(factor_vars)), STRENGTH=character(length(factor_vars)), stringsAsFactors = F)  # init output dataframe
for (factor_var in factor_vars){
  all_iv[all_iv$VARS == factor_var, "IV"] <- InformationValue::IV(X=sig_var[, factor_var], Y=sig_var$churn)
  all_iv[all_iv$VARS == factor_var, "STRENGTH"] <- attr(InformationValue::IV(X=sig_var[, factor_var], Y=sig_var$churn), "howgood")
}

all_iv <- all_iv[order(-all_iv$IV), ]  # sort

all_iv
```

```{r}
sig_var <- sig_var[ , ! names(sig_var) %in% c("sesso", "nuovo_abb", "cambiocap0512", "agenzia_tipo")]
```

